services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  ws-server:
    build:
      context: ./server
      dockerfile: dockerfile
    container_name: ws-server
    ports:
      - "9001:9001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=tcp://redis:6379
    networks:
      - app-network

  http-server:
    build:
      context: ./client
      dockerfile: dockerfile
    container_name: http-server
    ports:
      - "3000:3000"
    depends_on:
      - ws-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data: